name: Weekly cross-browser testing

on:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  cross-browser:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1
      - name: Firefox Browser Tests
        uses: cypress-io/github-action@v1
        with:
          browser: firefox
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
      - name: Chrome Browser Tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          start: yarn start
          wait-on: 'http://localhost:3000'
