name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: "MyCustom Node12 Server"
        uses: actions/setup-node@v1 ## Github Action ??
        with:
          node-version: "12.x"

      - name: Npm install
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm start

        env:
          CYPRESS_RECORD-KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
