name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: "MyCustom Node12 Server"
        uses: actions/setup-node@v1 ## Github Action ??
        with:
          node-version: "12.x"

      - name: Npm install
        run: npm install
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: "Actions"
          ci-build-id: "${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"
          start: npm start

        env:
          CYPRESS_RECORD-KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
