name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: "MyCustom Node12 Server"
        uses: actions/setup-node@v1 ## Github Action ??
        with:
          node-version: "12.x"

      - name: Npm install
        run: npm install
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-actions@v2 
