name: JavaScript workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 ## Github Action ??
      - name: "MyCustom Node12 Server"
        uses: actions/setup-node@v1 ## Github Action ??
        with:
          node-version: "12.x"
      - name: "npm install, and test"
        run: |
          npm install
          npm test
        env:
          CI: true ## optional
      - name: "configure env"
        env:
          REACT_APP_DATASOURCE_URI: ${{ secrets.REACT_APP_DATASOURCE_URI }}
          REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
          REACT_APP_AUTH0_CLIENTID: ${{secrets.REACT_APP_AUTH0_CLIENTID}}
          REACT_APP_AUTH_AUDIENCE: ${{secrets.REACT_APP_AUTH_AUDIENCE}}
          REACT_APP_AUTH_URL: ${{secrets.REACT_APP_AUTH_URL}}
          REACT_APP_AUTH_CLIENT_ID: ${{secrets.REACT_APP_AUTH_CLIENT_ID}}
          REACT_APP_AUTH_CLIENT_SECRET: ${{secrets.REACT_APP_AUTH_CLIENT_SECRET}}
          REACT_APP_AUTH_USERNAME: ${{secrets.REACT_APP_AUTH_USERNAME}}
          REACT_APP_AUTH_PASSWORD: ${{secrets.REACT_APP_AUTH_PASSWORD}}